name = "shared-auth-key-generator"
main = "src/index.ts"
compatibility_date = "2024-03-04"

[limits]
cpu_ms = 50

[triggers]
crons = [ "0 12 1 * *" ]

[[kv_namespaces]]
binding = "KV"
id = "e4447eea9a6c4fa588235e8e2ea12182"
